/**
 * Inycharge
 * Api definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pedro120919934@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Organization { 
    id?: string;
    name?: string;
    legalEntity?: string;
}
