/**
 * Inycharge
 * Api definition
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pedro120919934@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { ChargePoint } from '../model/chargePoint';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ChargePointService {

    protected basePath = 'http://localhost:8000/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addChargePoint(body: ChargePoint, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public addChargePoint(body: ChargePoint, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public addChargePoint(body: ChargePoint, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public addChargePoint(body: ChargePoint, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling addChargePoint.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/charge_point`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param chargePointId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteChagerPoint(chargePointId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteChagerPoint(chargePointId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteChagerPoint(chargePointId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteChagerPoint(chargePointId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (chargePointId === null || chargePointId === undefined) {
            throw new Error('Required parameter chargePointId was null or undefined when calling deleteChagerPoint.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/charge_point/${encodeURIComponent(String(chargePointId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllChargerPoints(observe?: 'body', reportProgress?: boolean): Observable<Array<ChargePoint>>;
    public getAllChargerPoints(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ChargePoint>>>;
    public getAllChargerPoints(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ChargePoint>>>;
    public getAllChargerPoints(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<ChargePoint>>(`${this.basePath}/charge_point`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find charge point by ID
     * 
     * @param chargePointId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getChargePointById(chargePointId: string, observe?: 'body', reportProgress?: boolean): Observable<ChargePoint>;
    public getChargePointById(chargePointId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ChargePoint>>;
    public getChargePointById(chargePointId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ChargePoint>>;
    public getChargePointById(chargePointId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (chargePointId === null || chargePointId === undefined) {
            throw new Error('Required parameter chargePointId was null or undefined when calling getChargePointById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ChargePoint>(`${this.basePath}/charge_point/${encodeURIComponent(String(chargePointId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param chargePointId 
     * @param chargePoint 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateChargePoint(chargePointId: string, chargePoint: ChargePoint, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateChargePoint(chargePointId: string, chargePoint: ChargePoint, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateChargePoint(chargePointId: string, chargePoint: ChargePoint, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateChargePoint(chargePointId: string, chargePoint: ChargePoint, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (chargePointId === null || chargePointId === undefined) {
            throw new Error('Required parameter chargePointId was null or undefined when calling updateChargePoint.');
        }

        if (chargePoint === null || chargePoint === undefined) {
            throw new Error('Required parameter chargePoint was null or undefined when calling updateChargePoint.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/charge_point/${encodeURIComponent(String(chargePointId))}`,
            chargePoint,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
